spring:
  session:
      store-type: redis #开启session共享
      timeout: 2592000
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.146.1:8848
    gateway:
      routes:
        - id: xyoj-backend-user-service
          uri: lb://xyoj-backend-user-service
          predicates:
            - Path=/api/user/**
        - id: xyoj-backend-question-service
          uri: lb://xyoj-backend-question-service
          predicates:
            - Path=/api/question/**
        - id: xyoj-backend-judge-service
          uri: lb://xyoj-backend-judge-service
          predicates:
            - Path=/api/judge/**
  application:
    name: xyoj-backend-gateway
  main:
    web-application-type: reactive
server:
  port: 8104
  servlet:
    context-path: /api
knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: swagger2